# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-059637cf-702c-49dc-b8ca-6eaa69d89677";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-059637cf-702c-49dc-b8ca-6eaa69d89677".device = "/dev/disk/by-uuid/059637cf-702c-49dc-b8ca-6eaa69d89677";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B784-8DDE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c871bb59-eb54-4c23-9f32-f17ce20cf2d9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
